# Spring Boot application properties file

# REST API configuration
spring.application.name=iso-8583-simulator-backend-rbm
server.port=9090

# Database source configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.initialization-mode=always
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# H2 database configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs configuration
logging.level.com.stiiven0rtiz=DEBUG

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Netty server configuration
netty.port=${NETTY_PORT}
netty.close.timeout.hours=${NETTY_CLOSE_TIMEOUT_HOURS}
netty.bosses.threads=${NETTY_B_T}
netty.workers.threads=${NETTY_W_T}
netty.frame.threads=${NETTY_F_T}
netty.constructor.threads=${NETTY_C_T}
netty.response.threads=${NETTY_R_T}
netty.persistence.threads=${NETTY_P_T}
netty.decoder.maxErrors=${NETTY_MAX_ERRORS}

# iso8583 configuration
iso-config.file=settings/iso8583-config.json
iso-config.transactions=settings/transactions/
iso-config.artificialDelayFilePath=settings/global/artificial-delay.json
iso-config.responseCodesFilePath=settings/global/terminal-code-responses.json
iso-config.posTerminalesFilePath=settings/global/pos-terminals.json
iso-config.transactionNamesFilePath=settings/global/transactions-names.json

# binChecker configuration
bin-checker.binlist.filepath=settings/bin_list/bin_list.csv
bin-checker.franchises_brands.filepath=settings/bin_list/franchises_brands.csv
bin-checker.types_card.filepath=settings/bin_list/types_card.csv

# HTTP client configuration
http-config.PathsFilePath=settings/http/paths.json
http-config.DefaultResponseFilePath=settings/http/default-http-response.json